import {
  AdminApplication,
  AdminAuthorization,
  AdminAuditLogEntry,
  AdminAuthorizationStatus,
  AdminPermissionRole,
  CodeScrietUser,
} from '../types';

export const BOOTSTRAP_ADMIN_EMAIL = 'applicationinformation73737@gmail.com';

export const INITIAL_ADMIN_AUTHORIZATIONS: AdminAuthorization[] = [
  {
    id: 'auth-bootstrap-master',
    userId: 'usr-bootstrap-admin',
    email: BOOTSTRAP_ADMIN_EMAIL,
    name: 'Code.SCRIET Master Admin',
    role: 'SUPER_ADMIN',
    verified: true,
    active: true,
    grantedAt: '2026-01-01T00:00:00.000Z',
    grantedBy: 'SYSTEM_BOOTSTRAP',
    notes: 'Official authoritative bootstrap administrator for Code.SCRIET platform',
  },
  {
    id: 'auth-kavita-02',
    userId: 'usr-kavita',
    email: 'kavita@scriet.ac.in',
    name: 'Kavita Rao',
    role: 'EVENT_ADMIN',
    verified: true,
    active: true,
    grantedAt: '2026-02-15T10:00:00.000Z',
    grantedBy: BOOTSTRAP_ADMIN_EMAIL,
    notes: 'Technical Lead for Event Operations & Scarcity Engine',
  },
];

export const INITIAL_ADMIN_APPLICATIONS: AdminApplication[] = [
  {
    id: 'app-priya-01',
    userId: 'usr-priya',
    name: 'Priya Sharma',
    email: 'priya@scriet.ac.in',
    status: 'PENDING',
    reason: 'Overseeing live floor logistics and team role token reissuances during Round 2 and Round 3.',
    requestedRole: 'EVENT_OPERATOR',
    submittedAt: '2026-02-25T11:30:00.000Z',
  },
  {
    id: 'app-rahul-02',
    userId: 'usr-rahul',
    name: 'Rahul Verma',
    email: 'rahul@scriet.ac.in',
    status: 'PENDING',
    reason: 'Assisting with auditorium live screen audio-visual feeds and scoring tally verification.',
    requestedRole: 'MODERATOR',
    submittedAt: '2026-02-25T14:15:00.000Z',
  },
  {
    id: 'app-kavita-03',
    userId: 'usr-kavita',
    name: 'Kavita Rao',
    email: 'kavita@scriet.ac.in',
    status: 'APPROVED',
    reason: 'Technical club lead for event platform operations and ledger reconciliation.',
    requestedRole: 'EVENT_ADMIN',
    submittedAt: '2026-02-14T09:00:00.000Z',
    reviewedAt: '2026-02-15T10:00:00.000Z',
    reviewedBy: 'Code.SCRIET Master Admin',
    reviewedByEmail: BOOTSTRAP_ADMIN_EMAIL,
  },
  {
    id: 'app-vikram-04',
    userId: 'usr-vikram',
    name: 'Vikram Singh',
    email: 'vikram@scriet.ac.in',
    status: 'REJECTED',
    reason: 'Wanting early access to event crisis cards for personal research.',
    requestedRole: 'ADMIN',
    submittedAt: '2026-02-20T16:00:00.000Z',
    reviewedAt: '2026-02-21T11:00:00.000Z',
    reviewedBy: 'Code.SCRIET Master Admin',
    reviewedByEmail: BOOTSTRAP_ADMIN_EMAIL,
    rejectionReason: 'Conflict of interest: applicant is competing on an active participating squad.',
  },
  {
    id: 'app-rohan-05',
    userId: 'usr-rohan',
    name: 'Rohan Mehta',
    email: 'rohan@scriet.ac.in',
    status: 'SUSPENDED',
    reason: 'Student coordinator volunteer.',
    requestedRole: 'EVENT_OPERATOR',
    submittedAt: '2026-02-10T12:00:00.000Z',
    reviewedAt: '2026-02-11T10:00:00.000Z',
    reviewedBy: 'Code.SCRIET Master Admin',
    reviewedByEmail: BOOTSTRAP_ADMIN_EMAIL,
    rejectionReason: 'Access revoked due to unauthorized device token broadcast.',
  },
];

export const INITIAL_ADMIN_AUDIT_LOGS: AdminAuditLogEntry[] = [
  {
    id: 'audit-001',
    actorUserId: 'system',
    actorEmail: 'system@scriet.dev',
    targetUserId: 'usr-bootstrap-admin',
    targetEmail: BOOTSTRAP_ADMIN_EMAIL,
    action: 'BOOTSTRAP_INITIAL_ADMIN',
    beforeStatus: 'NONE',
    afterStatus: 'SUPER_ADMIN',
    timestamp: '2026-01-01T00:00:00.000Z',
    reason: 'System bootstrap provisioning of authoritative administrator',
  },
  {
    id: 'audit-002',
    actorUserId: 'usr-bootstrap-admin',
    actorEmail: BOOTSTRAP_ADMIN_EMAIL,
    targetUserId: 'usr-kavita',
    targetEmail: 'kavita@scriet.ac.in',
    applicationId: 'app-kavita-03',
    action: 'ADMIN_APPLICATION_APPROVED',
    beforeStatus: 'PENDING',
    afterStatus: 'APPROVED (EVENT_ADMIN)',
    timestamp: '2026-02-15T10:00:00.000Z',
    reason: 'Verified as technical operations lead for Code.SCRIET flagship events',
  },
  {
    id: 'audit-003',
    actorUserId: 'usr-bootstrap-admin',
    actorEmail: BOOTSTRAP_ADMIN_EMAIL,
    targetUserId: 'usr-vikram',
    targetEmail: 'vikram@scriet.ac.in',
    applicationId: 'app-vikram-04',
    action: 'ADMIN_APPLICATION_REJECTED',
    beforeStatus: 'PENDING',
    afterStatus: 'REJECTED',
    timestamp: '2026-02-21T11:00:00.000Z',
    reason: 'Conflict of interest: applicant is competing on an active participating squad',
  },
  {
    id: 'audit-004',
    actorUserId: 'usr-bootstrap-admin',
    actorEmail: BOOTSTRAP_ADMIN_EMAIL,
    targetUserId: 'usr-rohan',
    targetEmail: 'rohan@scriet.ac.in',
    applicationId: 'app-rohan-05',
    action: 'ADMIN_ACCESS_SUSPENDED',
    beforeStatus: 'APPROVED',
    afterStatus: 'SUSPENDED',
    timestamp: '2026-02-24T18:00:00.000Z',
    reason: 'Access revoked due to unauthorized device token broadcast',
  },
];

// Persona presets for testing authentication and authorization transitions
export const PRESET_USERS: {
  user: CodeScrietUser;
  label: string;
  expectedStatus: AdminAuthorizationStatus;
  badge: string;
  description: string;
}[] = [
  {
    user: {
      id: 'usr-bootstrap-admin',
      name: 'Code.SCRIET Master Admin',
      email: BOOTSTRAP_ADMIN_EMAIL,
      role: 'SUPERADMIN',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    },
    label: 'Initial Bootstrap Super Admin',
    expectedStatus: 'ADMIN_VERIFIED',
    badge: 'SUPER_ADMIN',
    description: 'Initial authoritative administrator. Full Admin & Verification access.',
  },
  {
    user: {
      id: 'usr-aman-student',
      name: 'Aman Gupta',
      email: 'aman@scriet.edu',
      role: 'MEMBER',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    },
    label: 'Normal Student / Founder',
    expectedStatus: 'NORMAL_USER',
    badge: 'MEMBER',
    description: 'Standard campus founder. Admin button hidden. 403 on direct URL.',
  },
  {
    user: {
      id: 'usr-priya',
      name: 'Priya Sharma',
      email: 'priya@scriet.ac.in',
      role: 'USER',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    },
    label: 'Pending Admin Applicant',
    expectedStatus: 'ADMIN_PENDING',
    badge: 'PENDING',
    description: 'Applied for Event Operator. Awaiting review. No admin access.',
  },
  {
    user: {
      id: 'usr-kavita',
      name: 'Kavita Rao',
      email: 'kavita@scriet.ac.in',
      role: 'ADMIN',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    },
    label: 'Verified Event Admin',
    expectedStatus: 'ADMIN_VERIFIED',
    badge: 'EVENT_ADMIN',
    description: 'Approved administrator. Admin button visible.',
  },
  {
    user: {
      id: 'usr-rohan',
      name: 'Rohan Mehta',
      email: 'rohan@scriet.ac.in',
      role: 'USER',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    },
    label: 'Suspended Admin Account',
    expectedStatus: 'ADMIN_SUSPENDED',
    badge: 'SUSPENDED',
    description: 'Access revoked. Admin button hidden. Access denied.',
  },
];
