import { MarketItem, CrisisCard, Team, EventConfig, JudgingCriteria } from '../types/index';

export const DEFAULT_CONFIG: EventConfig = {
  id: 'zero-one-2026',
  name: 'ZERO → ONE 2026',
  slug: 'zero-one-2026',
  initialCapital: 1000000, // ₹10,00,000
  twoKeyApprovalThreshold: 100000, // Purchases >= ₹1,00,000 require CEO sign-off
  dynamicPricingEnabled: true,
  tradingEnabled: true,
  undoWindowSeconds: 60,
  roundDurationMinutes: 25,
  crisisResponseMinutes: 6,
  rngSeed: 'scriet-zero-one-flagship',
};

export const INITIAL_MARKET_ITEMS: MarketItem[] = [
  {
    sku: 'CLOUD-CREDITS',
    name: 'Cloud Credits',
    category: 'Infrastructure',
    basePrice: 80000,
    currentPrice: 96000,
    priceChangePct: 20,
    stockTotal: 15,
    stockRemaining: 12,
    unlocksDescription: 'Scalable server capacity and automated uptime monitoring.',
    effectSpec: { boostType: 'SPEED', value: 15 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Cloud',
  },
  {
    sku: 'MKT-CAMPAIGN',
    name: 'Marketing Campaign',
    category: 'Marketing',
    basePrice: 50000,
    currentPrice: 50000,
    priceChangePct: 0,
    stockTotal: 10,
    stockRemaining: 6,
    unlocksDescription: 'Targeted multi-channel student and early-adopter user acquisition.',
    effectSpec: { boostType: 'MARKET', value: 25 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Send',
  },
  {
    sku: 'DATA-ANALYTICS',
    name: 'Data Analytics Tool',
    category: 'Technology',
    basePrice: 120000,
    currentPrice: 108000,
    priceChangePct: -10,
    stockTotal: 8,
    stockRemaining: 4,
    unlocksDescription: 'Real-time telemetry and user conversion funnel analytics.',
    effectSpec: { boostType: 'HEALTH', value: 20 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'TrendingUp',
  },
  {
    sku: 'LEGAL-CONSULT',
    name: 'Legal Consultation',
    category: 'Operations',
    basePrice: 60000,
    currentPrice: 60000,
    priceChangePct: 0,
    stockTotal: 12,
    stockRemaining: 8,
    unlocksDescription: 'Regulatory compliance, IP trademarking, and terms protection.',
    effectSpec: { boostType: 'DEFENSE', value: 30 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Scale',
  },
  {
    sku: 'UIUX-EXPERT',
    name: 'UI/UX Expert',
    category: 'Human Resources',
    basePrice: 150000,
    currentPrice: 150000,
    priceChangePct: 0,
    stockTotal: 5,
    stockRemaining: 3,
    unlocksDescription: 'Design systems, high-converting product flows, and prototypes.',
    effectSpec: { boostType: 'HEALTH', value: 25 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Palette',
  },
  {
    sku: 'PROTOTYPE-KIT',
    name: 'Prototype Kit',
    category: 'Technology',
    basePrice: 90000,
    currentPrice: 90000,
    priceChangePct: 0,
    stockTotal: 10,
    stockRemaining: 6,
    unlocksDescription: 'CTO Build Station hardware and pre-configured deployment pipeline.',
    effectSpec: { boostType: 'SPEED', value: 35 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'FileCode',
  },
  {
    sku: 'CUSTOMER-RESEARCH',
    name: 'Customer Research',
    category: 'Marketing',
    basePrice: 70000,
    currentPrice: 63000,
    priceChangePct: -10,
    stockTotal: 12,
    stockRemaining: 10,
    unlocksDescription: 'Survey data from 500 validated university students and prospects.',
    effectSpec: { boostType: 'MARKET', value: 20 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Search',
  },
  {
    sku: 'OFFICE-BOOST',
    name: 'Office Space Boost',
    category: 'Operations',
    basePrice: 200000,
    currentPrice: 200000,
    priceChangePct: 0,
    stockTotal: 4,
    stockRemaining: 2,
    unlocksDescription: 'Dedicated incubator hub space with high-speed venue LAN connection.',
    effectSpec: { boostType: 'HEALTH', value: 30 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Building2',
  },
  {
    sku: 'DEVELOPER-HIRE',
    name: 'Senior Fullstack Dev',
    category: 'Human Resources',
    basePrice: 180000,
    currentPrice: 180000,
    priceChangePct: 0,
    stockTotal: 6,
    stockRemaining: 4,
    unlocksDescription: 'Unlocks CTO 20-minute rapid prototype build station.',
    effectSpec: { boostType: 'SPEED', value: 40 },
    visibleFromState: 'ROUND_1',
    status: 'AVAILABLE',
    icon: 'Code2',
  },
  {
    sku: 'MENTOR-SLOT',
    name: 'Angel Mentor 1-on-1',
    category: 'Growth',
    basePrice: 140000,
    currentPrice: 140000,
    priceChangePct: 0,
    stockTotal: 6,
    stockRemaining: 2,
    unlocksDescription: 'Pitch refinement, valuation advisory, and judge preparation.',
    effectSpec: { boostType: 'HEALTH', value: 35 },
    visibleFromState: 'ROUND_2',
    status: 'AVAILABLE',
    icon: 'GraduationCap',
  },
];

export const INITIAL_CRISIS_CARDS: CrisisCard[] = [
  {
    id: 'CRISIS-01',
    title: 'Competitor Price War',
    category: 'Market',
    severity: 'HIGH',
    description: 'A well-funded rival has slashed their subscription prices by 40% and launched aggressive college ads. Your customer conversions are plummeting.',
    timerSeconds: 360,
    shieldItemSku: 'CUSTOMER-RESEARCH',
    options: [
      {
        id: 'OPT-1',
        label: 'Increase Marketing Spend',
        cost: 70000,
        description: 'Launch defensive ad counter-blitz.',
        effectDescription: 'Retains 80% market share, prevents customer churn.',
        healthDelta: 5,
        requiresRoles: ['CFO', 'CMO'],
      },
      {
        id: 'OPT-2',
        label: 'Improve Product Features',
        cost: 100000,
        description: 'Ship 3 exclusive premium features competitors lack.',
        effectDescription: 'Positions as high-value option. Long-term defense.',
        healthDelta: 12,
        requiresRoles: ['CEO', 'CTO'],
      },
      {
        id: 'OPT-3',
        label: 'Do Nothing / Cut Costs',
        cost: 0,
        description: 'Preserve cash reserves and rely on organic loyalty.',
        effectDescription: 'Saves funds now, but reduces team health score by 15%.',
        healthDelta: -15,
      },
    ],
  },
  {
    id: 'CRISIS-02',
    title: 'Critical Database Outage',
    category: 'Technical',
    severity: 'CRITICAL',
    description: 'A major infrastructure provider suffers unexpected corruption. Users cannot complete transactions and error rates have spiked to 92%.',
    timerSeconds: 360,
    shieldItemSku: 'CLOUD-CREDITS',
    options: [
      {
        id: 'OPT-1',
        label: 'Hotfix & Failover Migration',
        cost: 60000,
        description: 'Deploy backup replication cluster immediately.',
        effectDescription: 'Restores stability in 5 minutes with zero data loss.',
        healthDelta: 10,
        requiresRoles: ['CTO'],
      },
      {
        id: 'OPT-2',
        label: 'Emergency Contractor Team',
        cost: 120000,
        description: 'Hire specialized database engineers on an hourly retainer.',
        effectDescription: 'Full restoration with comprehensive security audit.',
        healthDelta: 15,
        requiresRoles: ['CFO', 'CTO'],
      },
      {
        id: 'OPT-3',
        label: 'Public Apology & Maintenance Window',
        cost: 15000,
        description: 'Post downtime banner and rebuild gradually.',
        effectDescription: 'Damage to brand reputation; health score drops by 10%.',
        healthDelta: -10,
      },
    ],
  },
  {
    id: 'CRISIS-03',
    title: 'Seed Investor Backs Out',
    category: 'Financial',
    severity: 'HIGH',
    description: 'Your lead angel investor experienced liquidity issues and retracted their planned ₹3,00,000 convertible note commitment.',
    timerSeconds: 360,
    options: [
      {
        id: 'OPT-1',
        label: 'Take High-Interest Bridge Loan',
        cost: 25000,
        description: 'Secure emergency operational credit from fintech lender.',
        effectDescription: 'Maintains runway; requires repayment with 12% interest.',
        healthDelta: 0,
        requiresRoles: ['CFO'],
      },
      {
        id: 'OPT-2',
        label: 'Emergency Pitch Deck Pivot',
        cost: 40000,
        description: 'Fast-track customer pre-orders with annual discount packages.',
        effectDescription: 'Generates immediate organic revenue. Strengthens pitch.',
        healthDelta: 14,
        requiresRoles: ['CEO', 'CMO'],
      },
      {
        id: 'OPT-3',
        label: 'Freeze Non-Essential Hiring',
        cost: 0,
        description: 'Reduce operational burn rate to stretch current capital.',
        effectDescription: 'Slows down product velocity slightly (-5% health).',
        healthDelta: -5,
      },
    ],
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-07',
    teamCode: 'Team 07',
    name: 'InnovateX',
    problemStatement: 'Campus peer-to-peer textbook and lab hardware sharing marketplace.',
    targetCustomer: 'Engineering undergraduates at tier-2 and tier-3 colleges.',
    equitySoldPct: 5,
    healthScore: 68,
    healthBreakdown: {
      financial: 72,
      product: 65,
      marketing: 60,
      teamStability: 75,
    },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    activeCrisisId: 'CRISIS-01',
    createdAt: new Date().toISOString(),
    members: [
      {
        id: 'mem-1',
        userId: 'usr-101',
        displayName: 'Aman Gupta',
        email: 'aman@scriet.edu',
        role: 'CEO',
        deviceToken: 'dev-token-ceo-1',
        active: true,
        joinedAt: new Date().toISOString(),
        lastActiveAt: new Date().toISOString(),
      },
      {
        id: 'mem-2',
        userId: 'usr-102',
        displayName: 'Priya Sharma',
        email: 'priya@scriet.edu',
        role: 'CFO',
        deviceToken: 'dev-token-cfo-2',
        active: true,
        joinedAt: new Date().toISOString(),
        lastActiveAt: new Date().toISOString(),
      },
      {
        id: 'mem-3',
        userId: 'usr-103',
        displayName: 'Rohan Verma',
        email: 'rohan@scriet.edu',
        role: 'CTO',
        deviceToken: 'dev-token-cto-3',
        active: true,
        joinedAt: new Date().toISOString(),
        lastActiveAt: new Date().toISOString(),
      },
      {
        id: 'mem-4',
        userId: 'usr-104',
        displayName: 'Ananya Sen',
        email: 'ananya@scriet.edu',
        role: 'CMO',
        deviceToken: 'dev-token-cmo-4',
        active: true,
        joinedAt: new Date().toISOString(),
        lastActiveAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'team-01',
    teamCode: 'Team 01',
    name: 'TechNova',
    problemStatement: 'AI-assisted code debugging bot for university grading labs.',
    targetCustomer: 'Professors and TA graders at technological universities.',
    equitySoldPct: 8,
    healthScore: 76,
    healthBreakdown: { financial: 78, product: 80, marketing: 70, teamStability: 76 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-02',
    teamCode: 'Team 02',
    name: 'AgriNext',
    problemStatement: 'Hyperlocal drone-based soil moisture and pest scanning.',
    targetCustomer: 'Smallholder sugarcane farmers in Western Uttar Pradesh.',
    equitySoldPct: 10,
    healthScore: 71,
    healthBreakdown: { financial: 65, product: 75, marketing: 70, teamStability: 74 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-03',
    teamCode: 'Team 03',
    name: 'CodeCatalyst',
    problemStatement: 'Interactive competitive programming visualizer for beginners.',
    targetCustomer: 'Self-taught CS students preparing for campus placements.',
    equitySoldPct: 2,
    healthScore: 68,
    healthBreakdown: { financial: 69, product: 72, marketing: 62, teamStability: 69 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-04',
    teamCode: 'Team 04',
    name: 'Visionary',
    problemStatement: 'Smart wearable glasses for visually impaired campus navigation.',
    targetCustomer: 'Visually impaired university students and institutions.',
    equitySoldPct: 6,
    healthScore: 64,
    healthBreakdown: { financial: 60, product: 70, marketing: 58, teamStability: 68 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-05',
    teamCode: 'Team 05',
    name: 'NexGen',
    problemStatement: 'Green logistics electric-vehicle delivery fleet for colleges.',
    targetCustomer: 'E-commerce delivery partners and college food canteens.',
    equitySoldPct: 12,
    healthScore: 61,
    healthBreakdown: { financial: 58, product: 64, marketing: 60, teamStability: 62 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-06',
    teamCode: 'Team 06',
    name: 'StartSphere',
    problemStatement: 'Student founder angel micro-grant and escrow milestone network.',
    targetCustomer: 'Early student hackers needing ₹25k testing grants.',
    equitySoldPct: 4,
    healthScore: 58,
    healthBreakdown: { financial: 55, product: 60, marketing: 56, teamStability: 61 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-08',
    teamCode: 'Team 08',
    name: 'FutureFounders',
    problemStatement: 'Skill barter portal matching coders with designers.',
    targetCustomer: 'College hackathon participants seeking cross-functional teammates.',
    equitySoldPct: 0,
    healthScore: 54,
    healthBreakdown: { financial: 52, product: 55, marketing: 50, teamStability: 59 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-09',
    teamCode: 'Team 09',
    name: 'Ideatech',
    problemStatement: 'Automated patent and prior art search engine for research scholars.',
    targetCustomer: 'Postgraduate scholars and faculty patent cell.',
    equitySoldPct: 5,
    healthScore: 51,
    healthBreakdown: { financial: 48, product: 54, marketing: 49, teamStability: 53 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
  {
    id: 'team-10',
    teamCode: 'Team 10',
    name: 'BuildLoop',
    problemStatement: 'Continuous integration and test suite deployment for student projects.',
    targetCustomer: 'Computer science major semester project teams.',
    equitySoldPct: 0,
    healthScore: 48,
    healthBreakdown: { financial: 45, product: 50, marketing: 46, teamStability: 51 },
    status: 'ACTIVE',
    currentRound: 'Round 2 • Build & Grow',
    createdAt: new Date().toISOString(),
    members: [],
  },
];

export const DEFAULT_JUDGING_CRITERIA: JudgingCriteria[] = [
  { id: 'crit-problem', name: 'Problem Understanding & Validation', maxScore: 15, weight: 1.0 },
  { id: 'crit-innovation', name: 'Innovation & Differentiation', maxScore: 15, weight: 1.0 },
  { id: 'crit-business', name: 'Business Model & Unit Economics', maxScore: 20, weight: 1.0 },
  { id: 'crit-finance', name: 'Financial Thinking & Runway Management', maxScore: 15, weight: 1.0 },
  { id: 'crit-crisis', name: 'Crisis Response & Trade-off Agility', maxScore: 15, weight: 1.0 },
  { id: 'crit-pitch', name: 'Final Pitch Delivery & Defense', maxScore: 10, weight: 1.0 },
  { id: 'crit-feasibility', name: 'Technical Feasibility & Prototype', maxScore: 10, weight: 1.0 },
];
